{% raw %}- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', files) }}"
  vars:
    files:
      - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
      - "{{ ansible_facts.os_family }}.yml"
      - "{{ ansible_facts.os_distribution }}.yml"
      - none.yml

- include_tasks: "install-{{ ansible_facts.os_family }}.yml"{% endraw %}
